# Generated by Django 5.1.5 on 2025-01-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
        ('Guest', '0001_initial'),
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.tbl_product'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.customer'),
        ),
        migrations.AddField(
            model_name='boarding',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.pet'),
        ),
    ]
