# Generated by Django 5.1.5 on 2025-01-23 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_details', models.CharField(max_length=500)),
                ('product_rate', models.CharField(max_length=50)),
                ('product_photo', models.FileField(upload_to='Assets/ProductPhoto/')),
                ('stock', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.shop')),
            ],
        ),
    ]
