# Generated by Django 5.1.5 on 2025-01-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('ernakulam', 'Ernakulam'), ('kollam', 'Kollam'), ('idukki', 'Idukki')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Customer_image/')),
                ('proof', models.ImageField(upload_to='Customer_proof/')),
                ('is_admin', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('shop_type', models.CharField(choices=[('shop', 'Shop'), ('bording', 'Bording Service')], max_length=20)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('ernakulam', 'Ernakulam'), ('kollam', 'Kollam'), ('idukki', 'Idukki')], max_length=20)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=100)),
                ('proof', models.ImageField(upload_to='Shop_proof/')),
                ('Logo', models.ImageField(upload_to='Shop_logo/')),
            ],
        ),
    ]
