# Generated by Django 5.1.5 on 2025-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
